run:
  go: '1.22.2'

output:
  formats:
    - format: json
      path: stderr
    - format: checkstyle
      path: report.xml
    - format: colored-line-number
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - context
          - database/sql
          - fmt
          - log
          - github.com/mattn/go-sqlite3
          - embed
          - github.com/wailsapp/wails/v2
          - github.com/go-gorp/gorp
          - github.com/wailsapp/wails/v2/pkg/options
          - github.com/wailsapp/wails/v2/pkg/options/assetserver
          - testing
          - github.com/DATA-DOG/go-sqlmock
          - github.com/stretchr/testify/require

linters:
  enable-all: true
