// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:main.Instance):Promise<void>;

export function Clear():Promise<void>;

export function Delete(arg1:main.Instance):Promise<void>;

export function Get():Promise<Array<main.Instance>>;

export function Init():Promise<void>;

export function Set(arg1:Array<main.Instance>):Promise<void>;
