// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['InstanceApp']['Add'](arg1);
}

export function Clear() {
  return window['go']['main']['InstanceApp']['Clear']();
}

export function Delete(arg1) {
  return window['go']['main']['InstanceApp']['Delete'](arg1);
}

export function Get() {
  return window['go']['main']['InstanceApp']['Get']();
}

export function Set(arg1) {
  return window['go']['main']['InstanceApp']['Set'](arg1);
}
