// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChart(arg1) {
  return window['go']['main']['SqliteApp']['AddChart'](arg1);
}

export function AddInstance(arg1) {
  return window['go']['main']['SqliteApp']['AddInstance'](arg1);
}

export function ClearChart() {
  return window['go']['main']['SqliteApp']['ClearChart']();
}

export function ClearInstance() {
  return window['go']['main']['SqliteApp']['ClearInstance']();
}

export function DeleteChart(arg1) {
  return window['go']['main']['SqliteApp']['DeleteChart'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['SqliteApp']['DeleteInstance'](arg1);
}

export function GetChart() {
  return window['go']['main']['SqliteApp']['GetChart']();
}

export function GetInstance() {
  return window['go']['main']['SqliteApp']['GetInstance']();
}

export function SetChart(arg1) {
  return window['go']['main']['SqliteApp']['SetChart'](arg1);
}

export function SetInstance(arg1) {
  return window['go']['main']['SqliteApp']['SetInstance'](arg1);
}
