// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddChart(arg1:main.Chart):Promise<void>;

export function AddInstance(arg1:main.Instance):Promise<void>;

export function ClearChart():Promise<void>;

export function ClearInstance():Promise<void>;

export function DeleteChart(arg1:main.Chart):Promise<void>;

export function DeleteInstance(arg1:main.Instance):Promise<void>;

export function GetChart():Promise<Array<main.Chart>>;

export function GetInstance():Promise<Array<main.Instance>>;

export function SetChart(arg1:Array<main.Chart>):Promise<void>;

export function SetInstance(arg1:Array<main.Instance>):Promise<void>;
